from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import SnippetViewSet
from .auth_views import register, login, logout

# Router for ViewSet (handles CRUD automatically)
router = DefaultRouter()
router.register(r'snippets', SnippetViewSet, basename='snippet')

urlpatterns = [
    # Authentication endpoints
    path('auth/register/', register, name='register'),
    path('auth/login/', login, name='login'),
    path('auth/logout/', logout, name='logout'),
    
    # Snippet CRUD endpoints (auto-generated by router)
    # GET /api/snippets/ - List all snippets
    # POST /api/snippets/ - Create new snippet
    # GET /api/snippets/<id>/ - Retrieve specific snippet
    # PUT /api/snippets/<id>/ - Update snippet
    # DELETE /api/snippets/<id>/ - Delete snippet
    path('', include(router.urls)),
]